apiVersion: v1
kind: Pod
metadata:
  name: cap-sys-module
spec:
  containers:
  - name: container-escape-via-kernel-module
    image: "ubuntu:latest"
    command: ["/bin/sleep", "3650d"]
    securityContext:
      capabilities:
        add:
        - SYS_MODULE
